### ISSUE TITLE
Inquire to use schematic diagrams

### ISSUE THREAD

**Issue by paladin-t** [untoxa/gbvm#3]
Hello,

I hope this message finds you well. I am currently working on the development of GB BASIC, which is built upon the excellent GBVM library that you authored. Part of my current tasks involves drafting documentation for GB BASIC. I wanted to inquire whether it would be permissible for me to utilize the schematic diagrams you created for GBVM in explaining its principles within the documentation. Specifically, I am interested in using the sketches on the readme page of this repo, furthermore it would be much better if I could use more vectorized versions like the ones featured in articles such as https://gbstudiocentral.com/tips/understanding-gbvm/.

Best,
Tony

**Comment by untoxa** [comment]
Yes, you are welcome.

**Comment by paladin-t** [comment]
Thanks a lot!
